import { createHash } from 'node:crypto'
import { renderPetWindow } from './pet-renderer.js'

/** HTML 与脚本完全由 Desktop 提供；图集由已登录页面读取，原生窗口不发网络请求。 */
export function petWindowHtml(origin: string): string {
  const url = new URL(origin)
  if (url.origin !== origin || url.protocol !== 'http:' || !['127.0.0.1','localhost','[::1]'].includes(url.hostname)) throw new Error('宠物图片来源无效')
  const script = `(${renderPetWindow.toString()})()`
  const hash = createHash('sha256').update(script).digest('base64')
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; script-src 'sha256-${hash}'; style-src 'unsafe-inline'"><style>
  :root{color-scheme:light dark;--bg:#f7f7f7;--text:#252525;--muted:#727272;--line:#0002} @media(prefers-color-scheme:dark){:root{--bg:#292929;--text:#eee;--muted:#aaa;--line:#fff3}}
  *{box-sizing:border-box}html,body{margin:0;background:transparent!important;overflow:hidden;font:12px system-ui;color:var(--text)}button{font:inherit;color:inherit;border:0;background:transparent;cursor:pointer;padding:6px;border-radius:7px}button:hover{background:color-mix(in srgb,var(--text) 8%,transparent)}button:disabled{opacity:.5;cursor:default}button:focus-visible,textarea:focus-visible{outline:2px solid #4f8fff}svg{width:15px;height:15px;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round}.pet{position:absolute;right:12px;bottom:30px;padding:0;background:transparent!important;touch-action:none}.sprite{width:100%;height:100%;background-repeat:no-repeat;image-rendering:pixelated}.panel{position:absolute;right:12px;width:224px;padding:6px;overflow:auto;scrollbar-width:none}.panel[hidden]{display:none}.panel header{display:flex;justify-content:space-between;color:var(--muted)}article{position:relative;margin:5px 0 10px}.card{display:flex;gap:5px;align-items:center;min-height:54px;padding:7px 10px 7px 19px;border-radius:28px;border:1px solid var(--line);background:var(--bg);box-shadow:inset 0 1px 0 #ffffff0a,0 5px 12px #0003}.link{min-width:0;flex:1;text-align:left;padding:0}.link strong,.link span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;line-height:1.4}.link span{font-size:11px;color:var(--muted);margin-top:1px}.actions{display:flex;gap:6px}.icon{display:flex;align-items:center;justify-content:center;flex:none;border-radius:50%;width:28px;height:28px;padding:6px;background:color-mix(in srgb,var(--text) 8%,transparent);color:var(--muted)}.dismiss{position:absolute;z-index:1;left:-3px;top:-3px;width:19px;height:19px;padding:4px;border:1px solid var(--line);background:var(--bg)}.menu{width:160px;background:var(--bg);border:1px solid var(--line);border-radius:12px;padding:8px}.menu button{display:block;width:100%;text-align:left;padding:9px 6px}.request{margin-top:7px;padding:10px;background:var(--bg);border:1px solid var(--line);border-radius:14px}.request button{background:color-mix(in srgb,var(--text) 8%,transparent);margin:3px}.request p,legend{overflow-wrap:anywhere}fieldset{min-width:0;border:1px solid var(--line);margin:6px 0;padding:6px}label{display:block}small{display:block;color:var(--muted);padding-left:20px}pre{white-space:pre-wrap;font:inherit;max-height:140px;overflow:auto}textarea{width:100%;min-height:54px;resize:vertical;border:1px solid var(--line);border-radius:6px;padding:6px;background:var(--bg);color:var(--text);font:inherit}.error{padding:10px;background:var(--bg);border-radius:8px;color:#e55;overflow-wrap:anywhere}
  </style></head><body><script>${script}</script></body></html>`
}
